base_images:
  base:
    name: "4.18"
    namespace: ocp
    tag: base
build_root:
  project_image:
    dockerfile_path: ./Containerfile
promotion:
  to:
  - name: "4.18"
    namespace: ocp
releases:
  initial:
    integration:
      name: "4.18"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.18"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
zz_generated_metadata:
  branch: main
  org: openshift
  repo: insights-runtime-extractor
